agent_name: "cot"
mode: "json"
response_format:
  type: "json_object"
  # json_schema:
  #   name: "math_reasoning"
  #   schema:
  #     type: "object"
  #     properties:
  #       reasoning:
  #         type: "string"
  #       answer:
  #         type: "string"
  #     required:
  #       - reasoning
  #       - answer
  #     additionalProperties: false
  #   strict: true
# LLM hyperparameters
llm:
  series: "openai"  # ["anthropic", "gemini_dev"]
  model_name: "gpt-4o-2024-05-13"  # ["claude-3-haiku-20240307", "gemini-1.0-pro-001"]
  temperature: 0.0
  max_tokens: 2048
