agent_name: "fewshot"
# LLM hyperparameters
llm:
  series: "openai"  # ["anthropic", "gemini_dev"]
  model_name: "gpt-3.5-turbo-0125"  # ["claude-3-haiku-20240307", "gemini-1.0-pro-001"]
  temperature: 0.0
  max_tokens: 64
