agent_name: "ma_rr"
seed: 42
warmup_steps: 0
# LLM hyperparameters
llms:
  - series: "openai"
    model_name: "gpt-3.5-turbo-0125"
    temperature: 0.0
    max_tokens: 16  # Text-to-SQL / DS-1000: 512; Toolbench: 256; DDXPlus: 16
  - series: "gemini_dev"
    model_name: "gemini-1.0-pro-001"
    temperature: 0.0
    max_tokens: 32
  - series: "anthropic"
    model_name: "claude-3-haiku-20240307"
    temperature: 0.0
    max_tokens: 64  # DDXPlus: 64
# RAG configurations
rag:
  embedding_model: "BAAI/bge-base-en-v1.5"
  top_k: 16
  order: "similar_at_bottom"  # ["similar_at_top", "similar_at_bottom", "random"]
  rag_filename: null
  seed: 42
