agent_name: "zeroshot"
# LLM hyperparameters
llm:
  series: "hf_model"  # ["openai", "anthropic", "gemini_dev"]
  model_name: "google/gemma-2-2b-it"  # ["claude-3-haiku-20240307", "gemini-1.0-pro-001"]
  temperature: 0.0
  max_tokens: 32
