agent_name: "zeroshot"
# LLM hyperparameters
llm:
  series: "openai"  # ["openai", "anthropic", "gemini_dev"]
  model_name: "gpt-4o-2024-08-06"  # ["claude-3-haiku-20240307", "gemini-1.0-pro-001"]
  temperature: 0.0
  max_tokens: 2048
  top_logprobs: 4
